project:
  type: website

website:
  back-to-top-navigation: true
  sidebar:
    title: "Data Science"
    background: light
    pinned: true
    style: "docked"
    search: true
    contents:
      - section: "STAT1010"
        contents:
          - text: "Contents"
            href: stat1010.qmd 
          - text: "Resources"
            href: index.qmd
      - section: "STAT2000"
        contents:
          - text: "Contents"
            href: stat2000.qmd 
          - text: "Resources"
            href: index.qmd      
      - section: "STAT3000"
        contents:
          - text: "Contents"
            href: stat3000.qmd 
          - text: "Resources"
            href: index.qmd
      - section: "STAT4500" 
        contents:
          - text: "Contents"
            href: stat4500.qmd 
          - text: "Resources"
            href: index.qmd
  page-footer: "Copyright 2026, Xiao Ling"
  
format:
  html:
    toc: true           
    toc-location: right  
    toc-depth: 4
    number-sections: true   
    page-layout: full
          